### ISSUE TITLE
Global is not defined error after install

### ISSUE THREAD

**Issue by etekumoses** [jpuri/react-draft-wysiwyg#1317]
I just installed it following the Docs but i keep getting this error..

setImmediate.js:13 Uncaught ReferenceError: global is not defined
    at node_modules/fbjs/lib/setImmediate.js (setImmediate.js:13:18)
    at __require (chunk-J43GMYXM.js?v=56e10efa:11:50)
    at node_modules/draft-js/lib/editOnBeforeInput.js (editOnBeforeInput.js:27:20)
    at __require (chunk-J43GMYXM.js?v=56e10efa:11:50)
    at node_modules/draft-js/lib/DraftEditorEditHandler.js (DraftEditorEditHandler.js:15:21)
    at __require (chunk-J43GMYXM.js?v=56e10efa:11:50)
    at node_modules/draft-js/lib/DraftEditor.react.js (DraftEditor.react.js:36:30)
    at __require (chunk-J43GMYXM.js?v=56e10efa:11:50)
    at node_modules/draft-js/lib/Draft.js (Draft.js:28:19)
    at __require (chunk-J43GMYXM.js?v=56e10efa:11:50)

**Comment by MarcoRettoreDev** [comment]
Add this on your index.html:
<script>
    const global = globalThis;
</script>

**Comment by ritik373** [comment]
Add this on your index.html:

<script> const global = globalThis; </script> 100% working

**Comment by DineshWebDev1** [comment]
Uncaught ReferenceError: React is not defined
    App App.jsx:6
    React 11
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-ERAOJNUZ.js:3
    js index.js:6
    __require chunk-ERAOJNUZ.js:3
    React 2
    __require chunk-ERAOJNUZ.js:3
    js React
    __require chunk-ERAOJNUZ.js:3
    js React
    __require chunk-ERAOJNUZ.js:3
    <anonymous> react-dom_client.js:37
App.jsx:6:40
    App App.jsx:6
    React 11
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-ERAOJNUZ.js:3
    js index.js:6
    __require chunk-ERAOJNUZ.js:3
    React 2
    __require chunk-ERAOJNUZ.js:3
    js React
    __require chunk-ERAOJNUZ.js:3
    js React
    __require chunk-ERAOJNUZ.js:3
    <anonymous> react-dom_client.js:37

After adding it, getting error like this in browser console.

**Comment by ares524** [comment]
> Add this on your index.html:
> 
> <script> const global = globalThis; </script> 100% working

Many thanks. @ritik373 and @MarcoRettoreDev

**Comment by iamshz97** [comment]
@HannahNguyen6729 

just wanted to share we've been following this approach for quite the sometime and certain packages causes build conflicts when we do so, based on our recent findings the recommended approach would be to 
(follow the 1st approach mentioned in the below so)

https://stackoverflow.com/questions/72114775/vite-global-is-not-defined

And also 

[The Vite docs warn against using define for global](https://vitejs.dev/config/shared-options.html#define), as it can replaces the string global everywhere in the code, not just when it's used as a variable name. So @Yairopro's answer is the way to go. – 
[Ethan](https://stackoverflow.com/users/5374560/ethan)
 [Feb 21 at 3:21](https://stackoverflow.com/questions/72114775/vite-global-is-not-defined#comment133235482_73541205)

**Comment by etekumoses** [comment]
Is your project a react app ?

**Comment by ReetiMauryaCrest** [comment]
@MarcoRettoreDev is there any reason why I need to add this script line? Is my app configuration wrong in some way or is it some conflict while using Vite?

**Comment by MarcoRettoreDev** [comment]
from here, I can't tell you if your app config is wrong. However i guess this package use the global variable "window", that most frameworks & bundlers doesn't use anymore, and maybe thats why we have to add it manually...
You have two options, you add it manually at your index.html with the script tag or you can configure global variable at your vite config file.
Both solutions should work
