### ISSUE TITLE
unmet peer dependency draft-js

### ISSUE THREAD

**Issue by hiei189** [jpuri/react-draft-wysiwyg#197]
Hi

First of all, thanks for the awesome work.

If I do `npm install --save draft-js` I get unmet dependency due to` 0.9.x` in `package.json`. So I have to install `0.9.x` but then I get `iterable.length has been deprecated` warning because of [draft issue](https://github.com/facebook/draft-js/issues/607).

**Comment by jpuri** [comment]
Hey Looks like its time for me to upgrade draft, I will do it soon.

**Comment by jpuri** [comment]
Plz check `react-draft-wysiwyg@1.7.0` released today.

**Comment by hiei189** [comment]
oh nice.

I still getting the same warning, though. any idea? I thought It was beacuse of draft version.

**Comment by hiei189** [comment]
Warning appears only when <Editor /> is controlled. Otherwise it works nice.

**Comment by jpuri** [comment]
Hey @hiei189 , can you paste the warning and also your code ?

**Comment by hiei189** [comment]
Sure. I'm using `redux-form` to make it controlled.

```
class EditorWrapper extends React.Component {
constructor(props){
	super(props);
	this.blankState = EditorState.createEmpty();
}
render () {
	const { input: { value, onChange } } = this.props;
	return(
		<Editor
			editorState={value || this.blankState} 
			onEditorStateChange={(newState) => { onChange(newState) }}
		/>
	);
}
}
```

and the warning is 

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Record.get (http://localhost:3000/static/js/bundle.js:88179:22)
    at isArrayLike (http://localhost:3000/static/js/bundle.js:63108:42)
    at keys (http://localhost:3000/static/js/bundle.js:64218:11)
    at baseGetAllKeys (http://localhost:3000/static/js/bundle.js:65102:17)
    at getAllKeys (http://localhost:3000/static/js/bundle.js:65074:11)
    at equalObjects (http://localhost:3000/static/js/bundle.js:64990:19)
    at baseIsEqualDeep (http://localhost:3000/static/js/bundle.js:64543:11)
    at baseIsEqual (http://localhost:3000/static/js/bundle.js:64451:11)
    at equalObjects (http://localhost:3000/static/js/bundle.js:65027:40)
    at baseIsEqualDeep (http://localhost:3000/static/js/bundle.js:64543:11)
```
it occurs everytime I focus/blur/write/etc the Editor component.

**Comment by kyle516** [comment]
@hiei189 You shouldn't pass the EditorState object as payload to redux-form directly, you can convert it into plain string value before pass to redux-form (also save in DB as string).

Like this
```
import { convertToRaw, EditorState } from 'draft-js';

class EditorWrapper extends React.Component {

    constructor() {
        super();
        this.handleEditorStateChange = this.handleEditorStateChange.bind(this);
        this.state = {
            editorState: EditorState.createEmpty()
        }
    }

    convertToString(editorState) {
        return JSON.stringify(convertToRaw(editorState.getCurrentContent()));
    }

    handleEditorStateChange(editorState) {
        const { onChange } = this.props.input;
        const stringValue = this.convertToString(editorState);

        this.setState({ editorState });
        onChange(stringValue);
    }

    render() {
        return (
            <Editor
                editorState={this.state.editorState}
                onEditorStateChange={this.handleEditorStateChange} />
            );
        }
    }
}
```

**Comment by hiei189** [comment]
I see my error now, thanks. Sorry about it.
