### ISSUE TITLE
ERROR in ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.css

### ISSUE THREAD

**Issue by armmydev** [jpuri/react-draft-wysiwyg#321]
ERROR in ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.css
Module parse failed: /Users/armmydev/LocalCreativeTourism/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/armmydev/LocalCreativeTourism/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
 @ ./src/components/admin-add-content.js 17:0-59

**Comment by natashache** [comment]
@armmydev Did you find a solution for this? I'm getting the same error and I've had all the required dependencies installed.

**Comment by natashache** [comment]
Never mind. Installed css loader and changed webpack config. Working now.

**Comment by Huespal** [comment]
I've got the same error. Can you explain me how did you changed the webpack configuration? Thank you :)

**Comment by jpuri** [comment]
Docs here have similar webpack config: https://github.com/jpuri/react-draft-wysiwyg/tree/master/docs

https://github.com/jpuri/react-draft-wysiwyg/tree/master/docs/config
