### ISSUE TITLE
Failed to execute 'extend' on 'Selection'

### ISSUE THREAD

**Issue by Shadowman4205** [jpuri/react-draft-wysiwyg#587]
Hello,

Hello,i trying to create a simple table with modal  and form with one input where i pass  this array

```
[{
    "name": "Test",
    "age": "18"
}]
```
on add this is working. The problem is when i try add an Edit button. The model open, but when i try make a change on input, i cannot get fcused on it and  when i press to a any key i get this error:

```
node_modules\draft-js\lib\setDraftEditorSelection.js:217 Uncaught DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.
    at addFocusToSelection (http://localhost:3000/assets/vendor.js:50852:17)
    at setDraftEditorSelection (http://localhost:3000/assets/vendor.js:50786:5)
    at DraftEditorLeaf._setSelection (http://localhost:3000/assets/vendor.js:43425:5)
    at DraftEditorLeaf.componentDidUpdate (http://localhost:3000/assets/vendor.js:43435:10)
    at commitLifeCycles (http://localhost:3000/assets/vendor.js:134595:24)
    at commitAllLifeCycles (http://localhost:3000/assets/vendor.js:135372:9)
    at HTMLUnknownElement.callCallback (http://localhost:3000/assets/vendor.js:124377:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/assets/vendor.js:124416:16)
    at invokeGuardedCallback (http://localhost:3000/assets/vendor.js:124273:27)
    at commitAllWork (http://localhost:3000/assets/vendor.js:135493:9)
    at workLoop (http://localhost:3000/assets/vendor.js:135765:13)
    at HTMLUnknownElement.callCallback (http://localhost:3000/assets/vendor.js:124377:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/assets/vendor.js:124416:16)
    at invokeGuardedCallback (http://localhost:3000/assets/vendor.js:124273:27)
    at performWork (http://localhost:3000/assets/vendor.js:135878:7)
    at batchedUpdates (http://localhost:3000/assets/vendor.js:136322:9)
    at performFiberBatchedUpdates (http://localhost:3000/assets/vendor.js:124724:10)
    at stackBatchedUpdates (http://localhost:3000/assets/vendor.js:124715:10)
    at batchedUpdates (http://localhost:3000/assets/vendor.js:124729:10)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (http://localhost:3000/assets/vendor.js:124742:12)
    at dispatchEvent (http://localhost:3000/assets/vendor.js:124952:30)
```

![g](https://user-images.githubusercontent.com/23194476/35162222-533a7070-fd4b-11e7-86c4-0bb762d1070e.gif)

i tried the same thing on custom editor and the updating done without any error.
Why i get this error?

**Comment by jpuri** [comment]
@Shadowman4205 : can you plz share the code for this custom modal and edit button ?

**Comment by Shadowman4205** [comment]
This is the compnent for view table at edior with its button

```
class Table extends Component {
  static propTypes = {
    block: PropTypes.object,
    contentState: PropTypes.object
  };

  constructor(props) {
    super(props);

    this.state = {
      modalVisible: false
    };

    this.renderEditButton = this.renderEditButton.bind(this);
    this.openModal = this.openModal.bind(this);
    this.handleCancel = this.handleCancel.bind(this);
    this.renderTableTd = this.renderTableTd.bind(this);
    this._insert = this._insert.bind(this);
  }

  _insert(values, block, contentState) {
    const { config } = this.props.blockProps;

    const updatedData = values.table;
    const table = JSON.stringify(updatedData);
    const entityKey = block.getEntityAt(0);
    contentState.mergeEntityData(entityKey, { table });
    config.onChange(
      EditorState.push(
        config.getEditorState(),
        contentState,
        "change-block-data"
      )
    );

    this.setState({
      modalVisible: false
    });
  }

  openModal() {
    this.setState({
      modalVisible: true
    });
  }

  handleCancel() {
    this.setState({
      modalVisible: false
    });
  }

  renderEditButton() {
    return (
      <div>
        <Button onClick={this.openModal} size="small">
          <Icon type="edit" />
        </Button>
      </div>
    );
  }

  renderTableTd(raw, index) {
    const td = [];
    for (let key in raw) {
      td.push(<td key={`${key}_${index}`}>{raw[key]}</td>);
    }
    return td;
  }

  render() {
    const { block, contentState } = this.props;

    const entity = contentState.getEntity(block.getEntityAt(0));
    // const selectionState = editorState.getSelection();
    const { table } = entity.getData();
    const headers = getAvailableKeys(table);

    return (
      <div className="row">
        <div>
          <ModalForm
            visible={this.state.modalVisible}
            handleSubmit={values => this._insert(values, block, contentState)}
            handleCancel={this.handleCancel}
          />
        </div>
        {headers.length > 0 && (
          <div>
            <Button onClick={this.openModal} size="small">
              <Icon type="edit" />
            </Button>
            <table className="table">
              <thead>
                <tr>
                  {headers.map((item, index) => <th key={index}>{item}</th>)}
                </tr>
              </thead>
              <tbody>
                {table.map((item, index) => (
                  <tr key={index}>{this.renderTableTd(item, index)}</tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    );
  }
}
```
