### ISSUE TITLE
webpack css file is not loaded correctly. 

### ISSUE THREAD

**Issue by CHSquash** [jpuri/react-draft-wysiwyg#781]
node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css:1
(function (exports, require, module, __filename, __dirname) { .rdw-option-wrapper {
                                                              ^

SyntaxError: Unexpected token .
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:686:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)

my webpack config

```
module: {
        rules: [
            { 
                test: /\.js$/, 
                loader: 'babel-loader', 
                exclude: /immutable\.js$|draftjs-utils\.js$/ 
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                  fallback: 'style-loader',
                  use: 'css-loader?modules&importLoaders=1&localIdentName=[local]!postcss-loader',
                }),
            },
            { 
                test: /\.(png|jpg)$/, 
                loader: 'url-loader?limit=8192' 
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                loader: 'url-loader?limit=10000&mimetype=image/svg+xml',
            },
        ],
    },
```

**Comment by jpuri** [comment]
Hey @CHSquash : this issue does not seems related to the library but it appears related to you webpack configuration. You can refer this docs project: https://github.com/jpuri/react-draft-wysiwyg/tree/master/docs

It also importing and using `react-draft-wysiwyg.css`.
