### ISSUE TITLE
Warning: onDownArrow, onTab, onUpArrow has been deprecated

### ISSUE THREAD

**Issue by annammarri** [jpuri/react-draft-wysiwyg#853]
Hi, thankyou so much for this tool, it's great! 
When I run the editor, I can see 3 warnings in my console:
1. Supplying an `onDownArrow` prop to `DraftEditor` has been deprecated. If your handler needs access to the keyboard event, supply a custom `keyBindingFn` prop that falls back to the default one (eg. https://is.gd/RG31RJ).
2. Supplying an `onTab` prop to `DraftEditor` has been deprecated. If your handler needs access to the keyboard event, supply a custom `keyBindingFn` prop that falls back to the default one (eg. https://is.gd/RG31RJ).
3. Supplying an `onUpArrow` prop to `DraftEditor` has been deprecated. If your handler needs access to the keyboard event, supply a custom `keyBindingFn` prop that falls back to the default one (eg. https://is.gd/RG31RJ).

and I have these versions on my package.json:
"react": "^16.3.2"
"react-dom": "^16.3.2"
"react-draft-wysiwyg": "^1.13.2"
"draft-js": "^0.11.0"
"draftjs-to-html": "^0.8.4"

Thankyou for your help!

**Comment by BannukDE** [comment]
Update got published from draft.js 7 days ago. You could downgrade to 10.5 if you have issues other then deprecation warnings or do not want your console overflow while developing. I am looking for a long term fix as well.

**Comment by rinkisingh8181** [comment]
@jpuri 

Any suggestions with this one?

**Comment by aderbas** [comment]
+1

**Comment by vrbarros** [comment]
+1

**Comment by wamujlb** [comment]
@annammarri you can use my fork. I updated it: https://github.com/quriobot/react-draft-wysiwyg/tree/qb-changes

**Comment by sahiljaidka224** [comment]
Hi, 
Please fix this or provide a resolution. :/

**Comment by sahiljaidka224** [comment]
+1

**Comment by Krknv** [comment]
+1

**Comment by hivanreyes** [comment]
+1

**Comment by sahiljaidka224** [comment]
Hey guys,
Downgrade your react-draft libraries. "draft-js": "^0.10.5",
"draftjs-to-html": "^0.8.4",
"html-to-draftjs": "^1.4.0",
"react-draft-wysiwyg": "^1.13.2",

**Comment by juanlanus** [comment]
Is there any work being done towards upgrading this to consume DraftJS 0.11 instead of 0.10?
Because this is the real solution for this issue.
@wamujlb has a fork, is it possible to merge it?

**Comment by ferrao** [comment]
I guess the real problem is #879 :(

**Comment by sahiljaidka224** [comment]
@ferrao by downgrading you can ignore these warnings, please don't down vote if you don't know

**Comment by juanlanus** [comment]
As @ferrao said, #879 is at the root of the problem. 
Unless @jpuri passes the flag to somebody else ...

**Comment by ferrao** [comment]
> @ferrao by downgrading you can ignore these warnings, please don't down vote if you don't know

I downvoted in the sense that I do not think that is the solution for the problem. 
At most, that is a temporary workaround..

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.14.1` has the change.

**Comment by josephto** [comment]
@jpuri after updating to 1.14.1, i see this error now

`ReferenceError: window is not defined
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Object.<anonymous> (/Users/joseph/Development/tradewing/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.js:1:393)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Module._compile (module.js:653:30)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Module.Mp._compile (/Users/joseph/Development/tradewing/.meteor/local/build/programs/server/runtime.js:50:23)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Module.load (module.js:566:32)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Module.Mp.load (/Users/joseph/Development/tradewing/.meteor/local/build/programs/server/runtime.js:15:31)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at tryModuleLoad (module.js:506:12)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Function.Module._load (module.js:498:3)
[start] W20200102-15:25:59.156(-8)? (STDERR)     at Module.require (module.js:597:17)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at require (internal/module.js:11:18)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at npmRequire (/Users/joseph/Development/tradewing/.meteor/local/build/programs/server/npm-require.js:133:12)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at Module.useNode (packages/modules-runtime.js:664:18)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at react-draft-wysiwyg.js (packages/modules.js:1172:8)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at Module.moduleLink [as link] (/Users/joseph/.meteor/packages/modules/.0.14.0.bx2qwu.pkce++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at RichTextEditor.tsx (imports/ui/components/RichTextEditor.tsx:2:1)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
[start] W20200102-15:25:59.157(-8)? (STDERR)     at Module.moduleLink [as link] (/Users/joseph/.meteor/packages/modules/.0.14.0.bx2qwu.pkce++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
[start] W20200102-15:25:59.158(-8)? (STDERR)     at FeedItemCommentFormState.tsx (imports/ui/components/feed-item/FeedItemCommentFormState.tsx:1:1)
[start] W20200102-15:25:59.158(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)`
